repos:
  - repo: local
    hooks:
      - id: create-day-tiles
        name: create-day-tiles
        entry: python AoCTiles/create_aoc_tiles.py
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
